<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  

  <!-- PARAMETERS :: PARAMETERS :: PARAMETERS :: PARAMETERS -->
  <xacro:property name="chassis_width" value="0.2"/>
  <xacro:property name="chassis_length" value="0.4"/>
  <xacro:property name="chassis_height" value="0.1"/>
  
  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.05"/>
  
  <xacro:property name="caster_radius" value="0.05"/>
  <xacro:property name="wheel_separation"
		  value="${chassis_width + 1*wheel_width + 0.05}"/>
  <!-- xacro:property name="" value=""/ -->
    
  <!-- MACROS :: MACROS :: MACROS :: MACROS :: MACROS -->
  <xacro:macro name="unit_inertia" params="mass factor">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${factor}" iyy="${factor}" izz="${factor}"
	       ixy="0.0" ixz="0.0" iyz="0.0" />
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
    </inertial>
  </xacro:macro>

  
  <!-- GAZEBO COLORS :: GAZEBO COLORS :: GAZEBO COLORS -->
  <gazebo reference="RWheel" >
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="LWheel" >
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="camera" >
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="Chassis" >
    <material>Gazebo/Orange</material>
  </gazebo>


  <!-- This must follow definition of parameters not precede them -->
  <xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo" />


  <!-- JOINTS :: JOINTS :: JOINTS :: JOINTS :: JOINTS :: JOINTS -->
  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0.0 0.0 0.1" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="Chassis" />
  </joint>

  <joint name="left_wheel_hinge" type="continuous">
    <origin xyz="0.0 ${wheel_separation / 2.0} 0.0" rpy="0 0 0" />
    <child link="LWheel"/>
    <parent link="Chassis" />
    <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>
  
  <!-- 'continuous' joint type has no max/min limits -->
  <joint name="right_wheel_hinge" type="continuous">

    <child link="RWheel"/>
    <parent link="Chassis" />

    <!-- The child link relative to the parent -->
    <origin xyz="0.0 ${-1*wheel_separation / 2.0} 0.0" rpy="0 0 0" />

    <!-- Axis of revolution in the child frame -->
    <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>

  <joint name="Cam_joint" type="fixed">
    <origin xyz="0.219 0 0.02" rpy="0 0 0" />
    <child link="camera"/>
    <parent link="Chassis" />
    <!-- axis is not used with fixed joint types -->
  </joint>
  
  <joint name="Las_joint" type="fixed">
    <origin xyz="0.15 0 0.087" rpy="0 0 0" />
    <child link="hokuyo"/>
    <parent link="Chassis" />
    <!-- axis is not used with fixed joint types -->
  </joint>
  


  <!-- LINKS :: LINKS :: LINKS :: LINKS :: LINKS :: LINKS -->
  <link name="robot_footprint"></link>

  <!-- Chassis -->
  <link name='Chassis'>

    <xacro:unit_inertia mass="15.0" factor="1.0"/>

    <visual name='Chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
	<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange">
	<color rgba="1.0 0.55 0 1"/>
      </material>
    </visual>


    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
	<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>


    <!-- REAR CASTER -->
    <collision name='back_caster_collision'>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
	<sphere radius="${caster_radius}"/>
      </geometry>
    </collision>

    <visual name='back_caster_visual'>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
	<sphere radius="${caster_radius}"/>
      </geometry>
    </visual>

    <!-- FRONT CASTER -->
    <collision name='front_caster_collision'>
      <origin xyz="0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
	<sphere radius="${caster_radius}"/>
      </geometry>
    </collision>

    <visual name='front_caster_visual'>
      <origin xyz="0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
	<sphere radius="${caster_radius}"/>
      </geometry>
    </visual>

  </link>


  <!-- Left Wheel -->
  <link name="LWheel">

    <xacro:unit_inertia mass="3.0" factor="0.1"/>
    
    <visual name='LWheel_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
	<cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <material name="tire">
	<color rgba="0 0 0 1"/>
      </material>
    </visual>
    
    <collision name='LWheel_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
	<cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
    
  </link>


  <!-- Left Wheel -->
  <link name="RWheel">
    
    <xacro:unit_inertia mass="3.0" factor="0.1"/>
    
    <visual name='RWheel_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
	<cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <material name="tire">
	<color rgba="0 0 0 1"/>
      </material>
    </visual>
    
    <collision name='RWheel_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
	<cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
    
  </link>


  <!-- SENSORS :: SENSORS :: SENSORS :: SENSORS :: SENSORS :: SENSORS -->
  <link name="hokuyo">
    <xacro:unit_inertia mass="0.02" factor="0.002"/>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"  />
      <geometry>
	<box size="0.1 0.1 0.1" />
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<mesh filename="package://my_robot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>
  

  <link name="camera">
    <xacro:unit_inertia mass="0.08" factor="0.01"/>
    <visual name='camera_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.036 0.07 0.024" />
      </geometry>
      <!-- material name="cyan"/ -->
    </visual>
    <collision name='camera_collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.038 0.08 0.055" />
      </geometry>
    </collision>
  </link>

  
</robot>
